// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlerrwclehsegppzeqix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZXJyd2NsZWhzZWdwcHplcWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODczNTMsImV4cCI6MjA3MjU2MzM1M30.dzvmy7kc_t7VpiwjjZq-Hvpsx6o9xK3o2eSQG2Mg7BE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});